on:
   workflow_dispatch:
    inputs:
        name:
            city:"hyderabad"
            description: "Name"
            required: true
            type: "string"
            default: "Aditya"

jobs:
   greet:
      runs-on: ubuntu-latest
      steps:
         - name: checkout
           uses: actions/checkout@v4

         - name: greet
           run: echo "Hello World"
